### ISSUE TITLE
機能追加要望：リバースジオコーディング時に郵便番号も取得したい

### ISSUE THREAD

**Issue by satoru-naito-private** [t-sagara/jageocoder-server#5]
誠に勝手ながら、機能追加の要望です。
リバース住所ジオコーディングAPI実行時に、郵便番号も取得できるようにしていただきたいです。
こちらのAPIは精度が高く気に入っています。
ただ、郵便番号を取得しようとすると、住所解析から調べるをえず、大量のデータをさばけません。
ご検討お願いします。

**Comment by t-sagara** [comment]
@satoru-naito-private v1.0.6 で郵便番号の取得にも対応しましたのでお試しください。

**Comment by satoru-naito-private** [comment]
ありがとうございます！郵便番号が取得できるようになっていることを確認できました。
