### ISSUE TITLE
機能追加要望：リバースジオコーディングの速度を上げたい

### ISSUE THREAD

**Issue by satoru-naito-private** [t-sagara/jageocoder-server#6]
リバース住所ジオコーディングAPIの速度がより速いと便利だと感じています。
現在リバースジオコーディングを行うと、3つの住所が取得できますが、これを最も近い１点のみ返却するようにした場合、速度は上がりませんでしょうか？もし上がるのであれば、そういったオプションを追加していただきたいです。
ご検討お願いいたします。

**Comment by t-sagara** [comment]
@satoru-naito-private 試してみましたがほとんど改善しませんでした。
特殊なケースで遅くなっている可能性もありますので、特に遅いと感じる座標などがあればご報告ください。

**Comment by satoru-naito-private** [comment]
こちら特定のケースというよりは、大量のデータをさばこうとした場合に、トータルの時間が長くなってしまうことが気になっておりました。ご対応ありがとうございました。

**Comment by t-sagara** [comment]
@satoru-naito-private こちらの件ですが、 Jageocoder v2.1.7 で改善しました。
R-tree をこれまでの「大字・字」レベルから「街区・地番」レベルに変更したため、rtree.dat, rtree.idx ファイルを作り直していただく必要がありますが、お試しください。
